version: '3.9'

services:
  mysql:
    image: mysql/mysql-server:8.0.23
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ROOT_HOST: "%"
    command: --lower_case_table_names=1
    stdin_open: true
    tty: true
 
volumes:
    mysql-data:
